// Core accounting data model & double-entry engine.
//
// This is the anti-double-counting layer: the user never enters raw debits/credits.
// They pick "what happened" (a Recipe) and the app applies the correct debit/credit
// pair under the hood. A bank deposit that pays an invoice clears the receivable —
// it never creates new income.
//
// NOTE — VAT hook: the company is not VAT-registered yet. When that changes, VAT
// will be added as an extra split on relevant recipes (e.g. sale -> Dr Bank /
// Cr Sales + Cr VAT Output). No VAT fields exist anywhere in the app for now.

import { MONTHS, parseISO } from "./format";
import { Period, inPeriod } from "./period";

export type AcctType = "asset" | "liability" | "equity" | "income" | "expense";

export interface Account {
  id: string;
  name: string;
  type: AcctType;
  bank?: boolean;
}

export interface Txn {
  id: string;
  date: string; // ISO yyyy-mm-dd
  desc: string;
  amount: number; // always positive; debit/credit determine direction
  debit: string; // account id
  credit: string; // account id
  recipe: string; // recipe id, for display/audit purposes
  /** Set when the entry was generated by an invoice, so it can't be hand-edited. */
  sourceDoc?: string;
  /** Set on every change; drives last-write-wins during cloud sync. */
  updatedAt?: number;
  /** Set instead of removing the record, so the deletion reaches other devices. */
  deletedAt?: number;
}

// Chart of accounts — seeded from the owner's real Sage accounts.
export const SEED_ACCOUNTS: Account[] = [
  { id: "bank", name: "FNB Bank Account", type: "asset", bank: true },
  { id: "inventory", name: "Inventory (Stock)", type: "asset" },
  { id: "receivables", name: "Trade Receivables", type: "asset" },
  { id: "sales", name: "Sales", type: "income" },
  { id: "other_income", name: "Other Income", type: "income" },
  { id: "cos", name: "Cost of Sales", type: "expense" },
  { id: "advertising", name: "Advertising", type: "expense" },
  { id: "bank_charges", name: "Bank Charges", type: "expense" },
  { id: "general", name: "General Expenses", type: "expense" },
  { id: "motor", name: "Motor Vehicle", type: "expense" },
  { id: "rent", name: "Rent Paid", type: "expense" },
  { id: "salaries", name: "Salaries & Wages", type: "expense" },
  { id: "telephone", name: "Telephone & Internet", type: "expense" },
  { id: "travel", name: "Travel & Accommodation", type: "expense" },
  { id: "owner_contrib", name: "Owner Contribution", type: "equity" },
  { id: "owner_draw", name: "Owner Drawings", type: "equity" },
];

export type RecipeDirection = "in" | "out";
export type RecipePick = "debit" | "credit";

export interface Recipe {
  id: string;
  label: string;
  hint: string;
  dir: RecipeDirection;
  debit: string;
  credit: string;
  /** If set, the user must pick which account fills this side of the entry. */
  pick?: RecipePick;
  /** Restricts the picker to accounts of these types. */
  pickTypes?: AcctType[];
}

// "Recipes": one tap -> a correct double entry.
export const RECIPES: Recipe[] = [
  {
    id: "sale_cash",
    label: "Sale (money in)",
    hint: "Cash sale paid straight into the bank",
    dir: "in",
    debit: "bank",
    credit: "sales",
    pick: "credit",
    pickTypes: ["income"],
  },
  {
    id: "invoice_paid",
    label: "Customer paid an invoice",
    hint: "Clears the receivable — never books new income",
    dir: "in",
    debit: "bank",
    credit: "receivables",
  },
  {
    id: "owner_in",
    label: "Owner put money in",
    hint: "Capital contribution, not revenue",
    dir: "in",
    debit: "bank",
    credit: "owner_contrib",
  },
  {
    id: "expense",
    label: "Business expense (money out)",
    hint: "Anything the business pays for",
    dir: "out",
    debit: "general",
    credit: "bank",
    pick: "debit",
    pickTypes: ["expense"],
  },
  {
    id: "buy_stock",
    label: "Bought stock (money out)",
    hint: "ASIC miners and hardware for resale",
    dir: "out",
    debit: "inventory",
    credit: "bank",
  },
  {
    id: "drawings",
    label: "Personal / drawings (money out)",
    hint: "Money taken out for personal use",
    dir: "out",
    debit: "owner_draw",
    credit: "bank",
  },
];

export function findRecipe(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id);
}

export function findAccount(accounts: Account[], id: string): Account | undefined {
  return accounts.find((a) => a.id === id);
}

export function accountName(accounts: Account[], id: string): string {
  return findAccount(accounts, id)?.name ?? id;
}

/**
 * Balance engine: debit adds, credit subtracts.
 *
 * The opening bank balance is posted as a real double entry — Dr Bank /
 * Cr Owner Contribution — rather than dropped into the bank on its own. Money
 * already in the business at the start is the owner's capital, and seeding it
 * one-sided would leave the trial balance permanently out by that amount.
 *
 * Income and liability/equity accounts naturally carry credit balances, which show
 * up as negative numbers here — flip the sign when displaying them. Asset/expense
 * accounts naturally carry debit (positive) balances.
 */
export function computeBalances(
  accounts: Account[],
  txns: Txn[],
  openingBank: number
): Record<string, number> {
  const b: Record<string, number> = {};
  accounts.forEach((a) => (b[a.id] = 0));

  if (openingBank !== 0) {
    b.bank += openingBank;
    b.owner_contrib -= openingBank;
  }

  for (const t of txns) {
    b[t.debit] = (b[t.debit] ?? 0) + t.amount;
    b[t.credit] = (b[t.credit] ?? 0) - t.amount;
  }
  return b;
}

/** Display balance: flips sign for accounts that naturally carry a credit balance. */
export function displayBalance(account: Account, raw: number): number {
  return account.type === "income" ||
    account.type === "liability" ||
    account.type === "equity"
    ? -raw
    : raw;
}

export interface ProfitAndLoss {
  income: number;
  expenses: number;
  net: number;
  incomeLines: { account: Account; amount: number }[];
  expenseLines: { account: Account; amount: number }[];
}

export function computeProfitAndLoss(
  accounts: Account[],
  balances: Record<string, number>
): ProfitAndLoss {
  let income = 0;
  let expenses = 0;
  const incomeLines: { account: Account; amount: number }[] = [];
  const expenseLines: { account: Account; amount: number }[] = [];

  for (const a of accounts) {
    const raw = balances[a.id] ?? 0;
    if (a.type === "income") {
      const v = -raw;
      income += v;
      if (v !== 0) incomeLines.push({ account: a, amount: v });
    }
    if (a.type === "expense") {
      expenses += raw;
      if (raw !== 0) expenseLines.push({ account: a, amount: raw });
    }
  }

  incomeLines.sort((x, y) => y.amount - x.amount);
  expenseLines.sort((x, y) => y.amount - x.amount);

  return { income, expenses, net: income - expenses, incomeLines, expenseLines };
}

export interface TrialBalanceRow {
  account: Account;
  debit: number;
  credit: number;
}

/**
 * Trial balance. Which column an account lands in follows the sign of its
 * balance, not the type of account it is: a positive (net debit) balance is a
 * debit, a negative one is a credit. That is what makes the two totals agree by
 * construction — every entry adds the same amount to one side and the other.
 */
export function computeTrialBalance(
  accounts: Account[],
  balances: Record<string, number>
): { rows: TrialBalanceRow[]; totalDebit: number; totalCredit: number; balanced: boolean } {
  const rows: TrialBalanceRow[] = [];
  let totalDebit = 0;
  let totalCredit = 0;

  for (const a of accounts) {
    const raw = balances[a.id] ?? 0;
    if (Math.abs(raw) < 0.005) continue;
    const debit = Math.max(raw, 0);
    const credit = Math.max(-raw, 0);
    rows.push({ account: a, debit, credit });
    totalDebit += debit;
    totalCredit += credit;
  }

  return {
    rows,
    totalDebit,
    totalCredit,
    balanced: Math.abs(totalDebit - totalCredit) < 0.005,
  };
}

export function topExpenses(
  accounts: Account[],
  balances: Record<string, number>,
  limit = 6
): { account: Account; amount: number }[] {
  return accounts
    .filter((a) => a.type === "expense")
    .map((a) => ({ account: a, amount: balances[a.id] ?? 0 }))
    .filter((e) => e.amount > 0)
    .sort((x, y) => y.amount - x.amount)
    .slice(0, limit);
}

// ---------------------------------------------------------------------------
// Derived series — for charts and drill-downs
// ---------------------------------------------------------------------------

export interface MonthPoint {
  key: string; // "2026-03"
  label: string; // "Mar"
  income: number;
  expenses: number;
  net: number;
}

/**
 * Money in/out per calendar month. "In" and "out" are judged by which side the
 * bank account sits on, so an invoice settlement counts as cash in without
 * being counted as income twice.
 */
export function monthlyCashFlow(txns: Txn[], months = 6, now = new Date()): MonthPoint[] {
  const points: MonthPoint[] = [];
  const index = new Map<string, MonthPoint>();

  for (let i = months - 1; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
    const point: MonthPoint = { key, label: MONTHS[d.getMonth()], income: 0, expenses: 0, net: 0 };
    points.push(point);
    index.set(key, point);
  }

  for (const t of txns) {
    const point = index.get(t.date.slice(0, 7));
    if (!point) continue;
    if (t.debit === "bank") point.income += t.amount;
    else if (t.credit === "bank") point.expenses += t.amount;
  }

  for (const p of points) p.net = p.income - p.expenses;
  return points;
}

/**
 * Running bank balance over the last N transactions affecting the bank,
 * oldest first — the series behind the dashboard sparkline.
 */
export function bankBalanceSeries(txns: Txn[], openingBank: number, points = 24): number[] {
  const bankTxns = txns
    .filter((t) => t.debit === "bank" || t.credit === "bank")
    .sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : a.id.localeCompare(b.id)));

  const series: number[] = [openingBank];
  let running = openingBank;
  for (const t of bankTxns) {
    running += t.debit === "bank" ? t.amount : -t.amount;
    series.push(running);
  }
  return series.length <= points ? series : series.slice(series.length - points);
}

export function txnsForAccount(txns: Txn[], accountId: string): Txn[] {
  return txns.filter((t) => t.debit === accountId || t.credit === accountId);
}

export function filterByPeriod(txns: Txn[], period: Period): Txn[] {
  return txns.filter((t) => inPeriod(t.date, period));
}

/** Free-text search across description, date and the accounts involved. */
export function searchTxns(txns: Txn[], accounts: Account[], query: string): Txn[] {
  const q = query.trim().toLowerCase();
  if (!q) return txns;
  return txns.filter((t) => {
    const names = `${accountName(accounts, t.debit)} ${accountName(accounts, t.credit)}`;
    return (
      t.desc.toLowerCase().includes(q) ||
      t.date.includes(q) ||
      names.toLowerCase().includes(q) ||
      String(t.amount).includes(q)
    );
  });
}

export function sortByDateDesc(txns: Txn[]): Txn[] {
  return [...txns].sort((a, b) =>
    a.date < b.date ? 1 : a.date > b.date ? -1 : b.id.localeCompare(a.id)
  );
}

/** The non-bank side of an entry — what the ledger row actually shows. */
export function counterAccountId(t: Txn): string {
  return t.debit === "bank" ? t.credit : t.debit;
}

export function isMoneyIn(t: Txn): boolean {
  return t.debit === "bank";
}

/** Guards against a date the user typed by hand landing in the far future. */
export function isReasonableDate(iso: string): boolean {
  const d = parseISO(iso);
  if (!d) return false;
  const year = d.getFullYear();
  return year >= 2000 && year <= new Date().getFullYear() + 1;
}
