import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";
import { Account, SEED_ACCOUNTS, Txn, computeBalances } from "./accounting";
import { BusinessDoc, postingsForDocs } from "./invoices";
import { StockMovement, postingsForMovements } from "./inventory";
import { Reconciliation } from "./reconcile";
import { CloudSession, SyncOutcome, live, stamp, syncOnce, tombstone } from "./sync";
import { clearSession, loadSession, saveSession } from "./cloudSession";
import { findProduct, productLabel } from "./catalogue";
import { EMPTY_LEDGER, Ledger, Settings, loadLedger, saveLedger } from "./storage";

interface LedgerContextValue {
  loading: boolean;
  accounts: Account[];
  /** Manual entries only — what the user can edit or delete. */
  manualTxns: Txn[];
  /** Manual entries plus everything generated by invoices. The books. */
  txns: Txn[];
  docs: BusinessDoc[];
  movements: StockMovement[];
  reconciliations: Reconciliation[];
  openingBank: number;
  settings: Settings;
  balances: Record<string, number>;
  addTxn: (txn: Txn) => Promise<void>;
  updateTxn: (txn: Txn) => Promise<void>;
  removeTxn: (id: string) => Promise<void>;
  saveDoc: (doc: BusinessDoc) => Promise<void>;
  removeDoc: (id: string) => Promise<void>;
  addMovement: (m: StockMovement) => Promise<void>;
  removeMovement: (id: string) => Promise<void>;
  addReconciliation: (r: Reconciliation) => Promise<void>;
  removeReconciliation: (id: string) => Promise<void>;
  setOpeningBank: (amount: number) => Promise<void>;
  updateSettings: (patch: Partial<Settings>) => Promise<void>;
  replaceLedger: (ledger: Ledger) => Promise<void>;
  exportSnapshot: () => Ledger;
  cloud: CloudSession | null;
  syncing: boolean;
  lastSync: SyncOutcome | null;
  connectCloud: (session: CloudSession) => Promise<void>;
  disconnectCloud: () => Promise<void>;
  syncNow: () => Promise<SyncOutcome>;
}

const LedgerContext = createContext<LedgerContextValue | undefined>(undefined);

export function LedgerProvider({ children }: { children: React.ReactNode }) {
  const [loading, setLoading] = useState(true);
  const [ledger, setLedger] = useState<Ledger>(EMPTY_LEDGER);
  const [cloud, setCloud] = useState<CloudSession | null>(null);
  const [syncing, setSyncing] = useState(false);
  const [lastSync, setLastSync] = useState<SyncOutcome | null>(null);

  useEffect(() => {
    let cancelled = false;
    Promise.all([loadLedger(), loadSession()]).then(([loaded, session]) => {
      if (cancelled) return;
      setLedger(loaded);
      setCloud(session);
      setLoading(false);
    });
    return () => {
      cancelled = true;
    };
  }, []);

  const persist = useCallback(async (next: Ledger) => {
    setLedger(next);
    await saveLedger(next);
  }, []);

  const addTxn = useCallback(
    (txn: Txn) => persist({ ...ledger, txns: [stamp(txn), ...ledger.txns] }),
    [ledger, persist]
  );

  const updateTxn = useCallback(
    (txn: Txn) =>
      persist({
        ...ledger,
        txns: ledger.txns.map((t) => (t.id === txn.id ? stamp(txn) : t)),
      }),
    [ledger, persist]
  );

  // Deleting marks rather than drops, so the deletion can reach other devices.
  // Tombstones are filtered out of everything the UI reads.
  const removeTxn = useCallback(
    (id: string) =>
      persist({
        ...ledger,
        txns: ledger.txns.map((t) => (t.id === id ? tombstone(t) : t)),
      }),
    [ledger, persist]
  );

  const saveDoc = useCallback(
    (doc: BusinessDoc) => {
      const exists = ledger.docs.some((d) => d.id === doc.id);
      const docs = exists
        ? ledger.docs.map((d) => (d.id === doc.id ? stamp(doc) : d))
        : [stamp(doc), ...ledger.docs];
      return persist({ ...ledger, docs });
    },
    [ledger, persist]
  );

  const removeDoc = useCallback(
    (id: string) =>
      persist({
        ...ledger,
        docs: ledger.docs.map((d) => (d.id === id ? tombstone(d) : d)),
      }),
    [ledger, persist]
  );

  const addMovement = useCallback(
    (m: StockMovement) => persist({ ...ledger, movements: [stamp(m), ...ledger.movements] }),
    [ledger, persist]
  );

  const removeMovement = useCallback(
    (id: string) =>
      persist({
        ...ledger,
        movements: ledger.movements.map((m) => (m.id === id ? tombstone(m) : m)),
      }),
    [ledger, persist]
  );

  const addReconciliation = useCallback(
    (r: Reconciliation) =>
      persist({ ...ledger, reconciliations: [stamp(r), ...ledger.reconciliations] }),
    [ledger, persist]
  );

  const removeReconciliation = useCallback(
    (id: string) =>
      persist({
        ...ledger,
        reconciliations: ledger.reconciliations.map((r) =>
          r.id === id ? tombstone(r) : r
        ),
      }),
    [ledger, persist]
  );

  const setOpeningBank = useCallback(
    (amount: number) =>
      persist({ ...ledger, openingBank: amount, openingBankUpdatedAt: Date.now() }),
    [ledger, persist]
  );

  const updateSettings = useCallback(
    (patch: Partial<Settings>) =>
      persist({
        ...ledger,
        settings: { ...ledger.settings, ...patch, updatedAt: Date.now() },
      }),
    [ledger, persist]
  );

  const replaceLedger = useCallback((next: Ledger) => persist(next), [persist]);

  const connectCloud = useCallback(async (session: CloudSession) => {
    setCloud(session);
    await saveSession(session);
  }, []);

  const disconnectCloud = useCallback(async () => {
    setCloud(null);
    setLastSync(null);
    await clearSession();
  }, []);

  const syncNow = useCallback(async (): Promise<SyncOutcome> => {
    if (!cloud) {
      const outcome = { ok: false, pushed: 0, pulled: 0, error: "Not connected." };
      setLastSync(outcome);
      return outcome;
    }
    setSyncing(true);
    try {
      const result = await syncOnce(cloud, ledger);
      if (result.outcome.ok) {
        await persist(result.ledger);
        setCloud(result.session);
        await saveSession(result.session);
      }
      setLastSync(result.outcome);
      return result.outcome;
    } finally {
      setSyncing(false);
    }
  }, [cloud, ledger, persist]);

  // Invoice and stock postings are derived, never stored — so a document or a
  // stock move and its ledger entries can't drift apart, and revenue can only
  // ever be recognised once.
  const liveTxns = useMemo(() => live(ledger.txns), [ledger.txns]);
  const liveDocs = useMemo(() => live(ledger.docs), [ledger.docs]);
  const liveMovements = useMemo(() => live(ledger.movements), [ledger.movements]);
  const liveReconciliations = useMemo(
    () => live(ledger.reconciliations),
    [ledger.reconciliations]
  );

  const allTxns = useMemo(
    () => [
      ...liveTxns,
      ...postingsForDocs(liveDocs),
      ...postingsForMovements(liveMovements, (id) => {
        const product = findProduct(id);
        return product ? productLabel(product) : id;
      }),
    ],
    [liveTxns, liveDocs, liveMovements]
  );

  const balances = useMemo(
    () => computeBalances(SEED_ACCOUNTS, allTxns, ledger.openingBank),
    [allTxns, ledger.openingBank]
  );

  const value = useMemo<LedgerContextValue>(
    () => ({
      loading,
      accounts: SEED_ACCOUNTS,
      manualTxns: liveTxns,
      txns: allTxns,
      docs: liveDocs,
      movements: liveMovements,
      reconciliations: liveReconciliations,
      openingBank: ledger.openingBank,
      settings: ledger.settings,
      balances,
      addTxn,
      updateTxn,
      removeTxn,
      saveDoc,
      removeDoc,
      addMovement,
      removeMovement,
      addReconciliation,
      removeReconciliation,
      setOpeningBank,
      updateSettings,
      replaceLedger,
      exportSnapshot: () => ledger,
      cloud,
      syncing,
      lastSync,
      connectCloud,
      disconnectCloud,
      syncNow,
    }),
    [
      loading,
      ledger,
      allTxns,
      balances,
      addTxn,
      updateTxn,
      removeTxn,
      saveDoc,
      removeDoc,
      addMovement,
      removeMovement,
      addReconciliation,
      removeReconciliation,
      setOpeningBank,
      updateSettings,
      replaceLedger,
      liveTxns,
      liveDocs,
      liveMovements,
      liveReconciliations,
      cloud,
      syncing,
      lastSync,
      connectCloud,
      disconnectCloud,
      syncNow,
    ]
  );

  return <LedgerContext.Provider value={value}>{children}</LedgerContext.Provider>;
}

export function useLedger(): LedgerContextValue {
  const ctx = useContext(LedgerContext);
  if (!ctx) throw new Error("useLedger must be used within a LedgerProvider");
  return ctx;
}
