import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";
import { Account, SEED_ACCOUNTS, Txn, computeBalances } from "./accounting";
import { BusinessDoc, postingsForDocs } from "./invoices";
import { StockMovement, postingsForMovements } from "./inventory";
import { findProduct, productLabel } from "./catalogue";
import { EMPTY_LEDGER, Ledger, Settings, loadLedger, saveLedger } from "./storage";

interface LedgerContextValue {
  loading: boolean;
  accounts: Account[];
  /** Manual entries only — what the user can edit or delete. */
  manualTxns: Txn[];
  /** Manual entries plus everything generated by invoices. The books. */
  txns: Txn[];
  docs: BusinessDoc[];
  movements: StockMovement[];
  openingBank: number;
  settings: Settings;
  balances: Record<string, number>;
  addTxn: (txn: Txn) => Promise<void>;
  updateTxn: (txn: Txn) => Promise<void>;
  removeTxn: (id: string) => Promise<void>;
  saveDoc: (doc: BusinessDoc) => Promise<void>;
  removeDoc: (id: string) => Promise<void>;
  addMovement: (m: StockMovement) => Promise<void>;
  removeMovement: (id: string) => Promise<void>;
  setOpeningBank: (amount: number) => Promise<void>;
  updateSettings: (patch: Partial<Settings>) => Promise<void>;
  replaceLedger: (ledger: Ledger) => Promise<void>;
  exportSnapshot: () => Ledger;
}

const LedgerContext = createContext<LedgerContextValue | undefined>(undefined);

export function LedgerProvider({ children }: { children: React.ReactNode }) {
  const [loading, setLoading] = useState(true);
  const [ledger, setLedger] = useState<Ledger>(EMPTY_LEDGER);

  useEffect(() => {
    let cancelled = false;
    loadLedger().then((loaded) => {
      if (cancelled) return;
      setLedger(loaded);
      setLoading(false);
    });
    return () => {
      cancelled = true;
    };
  }, []);

  const persist = useCallback(async (next: Ledger) => {
    setLedger(next);
    await saveLedger(next);
  }, []);

  const addTxn = useCallback(
    (txn: Txn) => persist({ ...ledger, txns: [txn, ...ledger.txns] }),
    [ledger, persist]
  );

  const updateTxn = useCallback(
    (txn: Txn) =>
      persist({ ...ledger, txns: ledger.txns.map((t) => (t.id === txn.id ? txn : t)) }),
    [ledger, persist]
  );

  const removeTxn = useCallback(
    (id: string) => persist({ ...ledger, txns: ledger.txns.filter((t) => t.id !== id) }),
    [ledger, persist]
  );

  const saveDoc = useCallback(
    (doc: BusinessDoc) => {
      const exists = ledger.docs.some((d) => d.id === doc.id);
      const docs = exists
        ? ledger.docs.map((d) => (d.id === doc.id ? doc : d))
        : [doc, ...ledger.docs];
      return persist({ ...ledger, docs });
    },
    [ledger, persist]
  );

  const removeDoc = useCallback(
    (id: string) => persist({ ...ledger, docs: ledger.docs.filter((d) => d.id !== id) }),
    [ledger, persist]
  );

  const addMovement = useCallback(
    (m: StockMovement) => persist({ ...ledger, movements: [m, ...ledger.movements] }),
    [ledger, persist]
  );

  const removeMovement = useCallback(
    (id: string) =>
      persist({ ...ledger, movements: ledger.movements.filter((m) => m.id !== id) }),
    [ledger, persist]
  );

  const setOpeningBank = useCallback(
    (amount: number) => persist({ ...ledger, openingBank: amount }),
    [ledger, persist]
  );

  const updateSettings = useCallback(
    (patch: Partial<Settings>) =>
      persist({ ...ledger, settings: { ...ledger.settings, ...patch } }),
    [ledger, persist]
  );

  const replaceLedger = useCallback((next: Ledger) => persist(next), [persist]);

  // Invoice and stock postings are derived, never stored — so a document or a
  // stock move and its ledger entries can't drift apart, and revenue can only
  // ever be recognised once.
  const allTxns = useMemo(
    () => [
      ...ledger.txns,
      ...postingsForDocs(ledger.docs),
      ...postingsForMovements(ledger.movements, (id) => {
        const product = findProduct(id);
        return product ? productLabel(product) : id;
      }),
    ],
    [ledger.txns, ledger.docs, ledger.movements]
  );

  const balances = useMemo(
    () => computeBalances(SEED_ACCOUNTS, allTxns, ledger.openingBank),
    [allTxns, ledger.openingBank]
  );

  const value = useMemo<LedgerContextValue>(
    () => ({
      loading,
      accounts: SEED_ACCOUNTS,
      manualTxns: ledger.txns,
      txns: allTxns,
      docs: ledger.docs,
      movements: ledger.movements,
      openingBank: ledger.openingBank,
      settings: ledger.settings,
      balances,
      addTxn,
      updateTxn,
      removeTxn,
      saveDoc,
      removeDoc,
      addMovement,
      removeMovement,
      setOpeningBank,
      updateSettings,
      replaceLedger,
      exportSnapshot: () => ledger,
    }),
    [
      loading,
      ledger,
      allTxns,
      balances,
      addTxn,
      updateTxn,
      removeTxn,
      saveDoc,
      removeDoc,
      addMovement,
      removeMovement,
      setOpeningBank,
      updateSettings,
      replaceLedger,
    ]
  );

  return <LedgerContext.Provider value={value}>{children}</LedgerContext.Provider>;
}

export function useLedger(): LedgerContextValue {
  const ctx = useContext(LedgerContext);
  if (!ctx) throw new Error("useLedger must be used within a LedgerProvider");
  return ctx;
}
