import React from "react";
import { StyleSheet, Text, View } from "react-native";
import { Gesture, GestureDetector } from "react-native-gesture-handler";
import Animated, {
  runOnJS,
  useAnimatedStyle,
  useSharedValue,
  withSpring,
  withTiming,
} from "react-native-reanimated";
import { Trash2 } from "lucide-react-native";
import { C, R, S, T } from "../lib/theme";
import * as haptics from "../lib/haptics";

interface SwipeableRowProps {
  children: React.ReactNode;
  onDelete: () => void;
  /** Disable the gesture for rows the user isn't allowed to remove. */
  enabled?: boolean;
}

const OPEN_X = -88;
const TRIGGER_X = -150;

/**
 * Swipe left to reveal delete; keep swiping past the trigger point to delete
 * outright. Rows generated by an invoice pass enabled={false}, since deleting
 * them independently would break the link to their document.
 */
export default function SwipeableRow({ children, onDelete, enabled = true }: SwipeableRowProps) {
  const x = useSharedValue(0);
  const height = useSharedValue<number | undefined>(undefined);

  const close = () => {
    x.value = withSpring(0, { damping: 20, stiffness: 220 });
  };

  const pan = Gesture.Pan()
    .enabled(enabled)
    .activeOffsetX([-12, 12])
    .failOffsetY([-10, 10])
    .onUpdate((e) => {
      x.value = Math.min(0, e.translationX);
    })
    .onEnd(() => {
      if (x.value < TRIGGER_X) {
        x.value = withTiming(-500, { duration: 180 });
        runOnJS(haptics.success)();
        runOnJS(onDelete)();
      } else if (x.value < OPEN_X / 2) {
        x.value = withSpring(OPEN_X, { damping: 20, stiffness: 220 });
        runOnJS(haptics.tap)();
      } else {
        x.value = withSpring(0, { damping: 20, stiffness: 220 });
      }
    });

  const rowStyle = useAnimatedStyle(() => ({ transform: [{ translateX: x.value }] }));
  const actionStyle = useAnimatedStyle(() => ({
    opacity: Math.min(1, Math.abs(x.value) / Math.abs(OPEN_X)),
  }));

  return (
    <View style={styles.wrap}>
      <Animated.View style={[styles.action, actionStyle]}>
        <Trash2 color={C.red} size={18} />
        <Text style={styles.actionText}>Delete</Text>
      </Animated.View>
      <GestureDetector gesture={pan}>
        <Animated.View style={[styles.row, rowStyle]} onTouchEnd={enabled ? undefined : close}>
          {children}
        </Animated.View>
      </GestureDetector>
    </View>
  );
}

const styles = StyleSheet.create({
  wrap: { position: "relative", justifyContent: "center" },
  row: { backgroundColor: C.bg },
  action: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: 88,
    alignItems: "center",
    justifyContent: "center",
    gap: S.xs,
    backgroundColor: C.redDim,
    borderRadius: R.sm,
  },
  actionText: { ...T.caption, color: C.red },
});
